name: 'abyssal-setup'
description: 'Install a version of the Abyssal tool'
inputs:
  abyssal-version:
    description: 'What version of Abyssal to install'
    required: false
    default: '0.1.2'
  abyssal-url:
    description: 'The url to download Abyssal from'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
