name: 'abyssal-setup'
description: 'Install a version of the Abyssal tool'
inputs:
  abyssal-version:
    description: 'What version of Abyssal to install'
    required: false
    default: 'v0.1.5'
  abyssal-url:
    description: 'The url to download Abyssal from'
    required: false
    default: 'https://github.com/camalot/abyssal/releases/download/{version}/abyssal-{platform}-{arch}.tar.gz'
runs:
  using: 'node20'
  main: 'dist/index.js'
